apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photo-api.fullname" . }}-rabbitmq-credentials
  labels:
    {{- include "photo-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.auth.username | quote }}
  password: {{ .Values.rabbitmq.auth.password | quote }}
{{- if .Values.otelCollector.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photo-api.fullname" . }}-grafana-credentials
  labels:
    {{- include "photo-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.otelCollector.auth.username | quote }}
  password: {{ .Values.otelCollector.auth.password | quote }}
{{- end }}
