name: deploy-infra-and-apis
on:
  push:
    paths:
      - "api/**"
  workflow_dispatch:

env:
  LOCATION: uksouth
  RG_NAME: photo-app-uksouth-rg
  PHOTO_API_NAME: photo-api
  PHOTO_API_PORT: 8080
  RESIZE_API_NAME: resize-api
  RESIZE_API_PORT: 8080
  VERSION: 1.0.0

jobs:
  deploy-acr-job:
    runs-on: ubuntu-latest
    outputs:
      acrName: ${{ steps.deploy-outputs.outputs.acrName }}
    steps:
      - name: checkout-code
        id: checkout-code
        uses: actions/checkout@main

      - name: login-azure
        id: login-azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: create-resource-group
        id: create-resource-group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.67.0
          inlineScript: |
            az group create --name ${{ env.RG_NAME }} --location ${{ env.LOCATION }}

      - name: deploy-acr
        id: deploy-acr
        uses:  azure/arm-deploy@v2
        with:
          deploymentName: deploy-acr
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: ./infra/modules/acr.bicep


      - name: deploy-outputs
        id: deploy-outputs
        run: |
          echo "acrName: ${{ steps.deploy-acr.outputs.acrName }}"
          echo "acrName=${{ steps.deploy-acr.outputs.acrName }}" >> "$GITHUB_OUTPUT"
  
  build-photo-api-job:
    runs-on: ubuntu-latest
    needs: [deploy-acr-job]
    outputs:
      photoApiImageName: ${{ steps.acr-build-photo-api.outputs.photoApiImage }}
    steps:
      - name: checkout-code
        id: checkout-code
        uses: actions/checkout@main

      - name: login-azure
        id: login-azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: acr-build-photo-api
        id: acr-build-photo-api
        uses: azure/cli@v2
        with:
          azcliversion: 2.67.0
          inlineScript: |
            az acr build \
              --registry ${{ needs.deploy-acr-job.outputs.acrName }} \
              -t "${{ needs.deploy-acr-job.outputs.acrName }}.azurecr.io/${{ env.PHOTO_API_NAME }}:${{ env.VERSION }}" \
              --build-arg SERVICE_NAME=${{ env.PHOTO_API_NAME }} \
              --build-arg SERVICE_PORT=${{ env.PHOTO_API_PORT }} \
              -f ./Dockerfile .
       
      - run: |
          echo "${{ needs.deploy-acr-job.outputs.acrName }}.azurecr.io/${{ env.PHOTO_API_NAME }}:${{ env.VERSION }}"
          echo "photoApiImage=${{ needs.deploy-acr-job.outputs.acrName }}.azurecr.io/${{ env.PHOTO_API_NAME }}:${{ env.VERSION }}" >> $GITHUB_OUTPUT

  build-resize-api-job:
    runs-on: ubuntu-latest
    needs: deploy-acr-job
    outputs:
      resizeApiImage: ${{ steps.acr-build-resize-api.outputs.resizeApiImage }}`
    steps:
      - name: checkout-code
        id: checkout-code
        uses: actions/checkout@main

      - name: login-azure
        id: login-azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: acr-build-resize-api
        id: acr-build-resize-api
        uses: azure/cli@v2
        with:
          azcliversion: 2.67.0
          inlineScript: |
            az acr build \
              --registry ${{ needs.deploy-acr-job.outputs.acrName }} \
              -t "${{ needs.deploy-acr-job.outputs.acrName }}.azurecr.io/${{ env.RESIZE_API_NAME }}:${{ env.VERSION }}" \
              --build-arg SERVICE_NAME=${{ env.RESIZE_API_NAME }} \
              --build-arg SERVICE_PORT=${{ env.RESIZE_API_PORT }} \
              -f ./Dockerfile .

      - run: |
          echo "${{ needs.deploy-acr-job.outputs.acrName }}.azurecr.io/${{ env.RESIZE_API_NAME }}:${{ env.VERSION }}"
          echo "resizeApiImage=${{ needs.deploy-acr-job.outputs.acrName }}.azurecr.io/${{ env.RESIZE_API_NAME }}:${{ env.VERSION }}" >> $GITHUB_OUTPUT

  build-and-deploy-infra-job:
    runs-on: ubuntu-latest
    needs: [deploy-acr-job, build-photo-api-job, build-resize-api-job]
    env:
      ACR_NAME: ${{ needs.deploy-acr-job.outputs.acrName }}
    steps:
    - name: checkout-code
      id: checkout-code
      uses: actions/checkout@main

    - name: login-azure
      id: login-azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy-infra
      id: deploy-infra
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        deploymentName: deploy-infra
        resourceGroupName: ${{ env.RG_NAME }}
        template: ./infra/main.bicep
        parameters: "acrName=${{ needs.deploy-acr-job.outputs.acrName }} photoApiContainerImage=${{ needs.build-photo-api-job.outputs.photoApiImageName }} resizeApiContainerImage=${{ needs.build-resize-api-job.outputs.resizeApiImage }}"
        failOnStdErr: true
