name: deploy-infra-and-apis
on:
  push:
    paths:
      - "api/**"
  workflow_dispatch:

env:
  LOCATION: westeurope
  APP_NAME: photo-app
  DNS_ZONE_RG_NAME: external-domain-rg
  TEMPLATE_FILE_PATH: ./infra/main.bicep
  PHOTO_API_NAME: photo
  PHOTO_API_PORT: 8080
  RESIZE_API_NAME: resize
  RESIZE_API_PORT: 8080
  VERSION: 1.0.0

jobs:
  deploy-acr-job:
    runs-on: ubuntu-latest
    outputs:
      acrName: ${{ steps.deploy-acr-outputs.outputs.acrName }}
      resizeApiImage: ${{ steps.deploy-acr-outputs.outputs.resizeApiImage }}
      photoApiImage: ${{ steps.deploy-acr-outputs.outputs.photoApiImage }}
      rgName: ${{ steps.gen-rg-name.outputs.rgName }}
    steps:
      - name: checkout-code
        id: checkout-code
        uses: actions/checkout@main

      - name: gen-rg-name
        id: gen-rg-name
        run: |
            echo "rgName: ${{ env.APP_NAME }}-${{ env.LOCATION }}-rg"
            echo "rgName=${{ env.APP_NAME }}-${{ env.LOCATION }}-rg" >> "$GITHUB_OUTPUT"
            echo "rgName=${{ env.APP_NAME }}-${{ env.LOCATION }}-rg" >> "$GITHUB_ENV"

      - name: short-sha
        id: short-sha
        run: |
            echo "sha: sha=$(git rev-parse --short HEAD)"
            echo "SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: login-azure
        id: login-azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: create-resource-group
        id: create-resource-group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.67.0
          inlineScript: |
            az group create --name $rgName --location ${{ env.LOCATION }}

      - name: deploy-acr
        id: deploy-acr
        uses:  azure/arm-deploy@v2
        with:
          deploymentName: deploy-acr
          resourceGroupName: $rgName
          template: ./infra/modules/acr.bicep

      - name: deploy-acr-outputs
        id: deploy-acr-outputs
        env:
          SHA: ${{ env.SHA }}
          ACR_NAME: ${{ steps.deploy-acr.outputs.acrName }}
        run: |
          echo "acrName: ${{ env.ACR_NAME }}"
          echo "acrName=${{ env.ACR_NAME }}" >> "$GITHUB_OUTPUT"
          echo "photoApiImage: ${{ env.ACR_NAME }}.azurecr.io/${{ env.PHOTO_API_NAME }}:${{ env.VERSION }}-$SHA"
          echo "photoApiImage=${{ env.ACR_NAME }}.azurecr.io/${{ env.PHOTO_API_NAME }}:${{ env.VERSION }}-$SHA" >> $GITHUB_OUTPUT
          echo "resizeApiImage: ${{ env.ACR_NAME }}.azurecr.io/${{ env.RESIZE_API_NAME }}:${{ env.VERSION }}-$SHA"
          echo "resizeApiImage=${{ env.ACR_NAME }}.azurecr.io/${{ env.RESIZE_API_NAME }}:${{ env.VERSION }}-$SHA" >> $GITHUB_OUTPUT

  build-photo-api-job:
    runs-on: ubuntu-latest
    needs: [deploy-acr-job]
    steps:
      - name: checkout-code
        id: checkout-code
        uses: actions/checkout@main

      - name: login-azure
        id: login-azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: acr-build-photo-api
        id: acr-build-photo-api
        uses: azure/cli@v2
        with:
          azcliversion: 2.67.0
          inlineScript: |
            az acr build \
              --registry ${{ needs.deploy-acr-job.outputs.acrName }} \
              -t "${{ needs.deploy-acr-job.outputs.photoApiImage }}" \
              --build-arg SERVICE_NAME=${{ env.PHOTO_API_NAME }} \
              --build-arg SERVICE_PORT=${{ env.PHOTO_API_PORT }} \
              -f ./Dockerfile .

  build-resize-api-job:
    runs-on: ubuntu-latest
    needs: deploy-acr-job
    steps:
      - name: checkout-code
        id: checkout-code
        uses: actions/checkout@main

      - name: login-azure
        id: login-azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: acr-build-resize-api
        id: acr-build-resize-api
        uses: azure/cli@v2
        with:
          azcliversion: 2.67.0
          inlineScript: |
            az acr build \
              --registry ${{ needs.deploy-acr-job.outputs.acrName }} \
              -t "${{ needs.deploy-acr-job.outputs.resizeApiImage }}" \
              --build-arg SERVICE_NAME=${{ env.RESIZE_API_NAME }} \
              --build-arg SERVICE_PORT=${{ env.RESIZE_API_PORT }} \
              -f ./Dockerfile .

  build-and-deploy-infra-job:
    runs-on: ubuntu-latest
    needs: [deploy-acr-job, build-photo-api-job, build-resize-api-job]
    steps:
    - name: checkout-code
      id: checkout-code
      uses: actions/checkout@main

    - name: login-azure
      id: login-azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy-infra-cli
      id: deploy-infra-cli
      uses: azure/cli@v2
      continue-on-error: false
      with:
        azcliversion: 2.67.0
        inlineScript: |
          az deployment group create \
            --name deploy-infra \
            --resource-group ${{ needs.deploy-acr-job.outputs.rgName}} \
            --template-file ${{ env.TEMPLATE_FILE_PATH }} \
            --parameters acrName=${{ needs.deploy-acr-job.outputs.acrName }} \
            --parameters photoApiContainerImage=${{ needs.deploy-acr-job.outputs.photoApiImage }} \
            --parameters resizeApiContainerImage=${{ needs.deploy-acr-job.outputs.resizeApiImage }} \
            --parameters dnsResourceGroupName=${{ env.DNS_ZONE_RG_NAME }}
            
    - name: deploy-infra-outputs
      id: deploy-infra-outputs
      uses: azure/cli@v2
      env:
        STORAGE_ACCOUNT_NAME: ${{ steps.deploy-infra-cli.outputs.storageAccountName }}
        PHOTO_API_URI: ${{ steps.deploy-infra-cli.outputs.photoApiEndpoint }}
        RESIZE_API_URI: ${{ steps.deploy-infra-cli.outputs.resizeApiEndpoint }}
      with:
        inlineScript: |
          # enable static website hosting
          az storage blob service-properties update --account-name $STORAGE_ACCOUNT_NAME --static-website --index-document index.html --404-document index.html
